version: '3.2'

services:
  db:
    image: bulmersolutions_db:latest
    volumes:
    - volume01:/var/lib/mysql/data
  web:
    image: bulmersolutions_web:latest
    ports:
    - "8080:8080"
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
    - NODE_ENV=production
    - VIRTUAL_HOST=bulmersolutions.com
    - LETSENCRYPT_HOST=bulmersolutions.com
    volumes:
    - ./web:/usr/src/website
    - volume01:/var/log
volumes:
  volume01: {}