version: '3.2'

services:
  db:
    build: ./mysql
    volumes:
    - volume01:/var/lib/mysql/data
  web:
    build: ./web
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
    volumes:
    - .:/code
    - volume01:/var/log
volumes:
  volume01: {}
